package com.danilovfa.deskmotion.ui.theme.color

val DeskMotionColorDarkPalette: DeskMotionThemeColors = DeskMotionThemeColors(
    primary = DeskMotionColor.md_theme_dark_primary,
    onPrimary = DeskMotionColor.md_theme_dark_onPrimary,
    primaryContainer = DeskMotionColor.md_theme_dark_primaryContainer,
    onPrimaryContainer = DeskMotionColor.md_theme_dark_onPrimaryContainer,
    secondary = DeskMotionColor.md_theme_dark_secondary,
    onSecondary = DeskMotionColor.md_theme_dark_onSecondary,
    secondaryContainer = DeskMotionColor.md_theme_dark_secondaryContainer,
    onSecondaryContainer = DeskMotionColor.md_theme_dark_onSecondaryContainer,
    tertiary = DeskMotionColor.md_theme_dark_tertiary,
    onTertiary = DeskMotionColor.md_theme_dark_onTertiary,
    tertiaryContainer = DeskMotionColor.md_theme_dark_tertiaryContainer,
    onTertiaryContainer = DeskMotionColor.md_theme_dark_onTertiaryContainer,
    error = DeskMotionColor.md_theme_dark_error,
    errorContainer = DeskMotionColor.md_theme_dark_errorContainer,
    onError = DeskMotionColor.md_theme_dark_onError,
    onErrorContainer = DeskMotionColor.md_theme_dark_onErrorContainer,
    background = DeskMotionColor.md_theme_dark_background,
    onBackground = DeskMotionColor.md_theme_dark_onBackground,
    surface = DeskMotionColor.md_theme_dark_surface,
    onSurface = DeskMotionColor.md_theme_dark_onSurface,
    surfaceVariant = DeskMotionColor.md_theme_dark_surfaceVariant,
    onSurfaceVariant = DeskMotionColor.md_theme_dark_onSurfaceVariant,
    outline = DeskMotionColor.md_theme_dark_outline,
    inverseOnSurface = DeskMotionColor.md_theme_dark_inverseOnSurface,
    inverseSurface = DeskMotionColor.md_theme_dark_inverseSurface,
    inversePrimary = DeskMotionColor.md_theme_dark_inversePrimary,
    surfaceTint = DeskMotionColor.md_theme_dark_surfaceTint,
    outlineVariant = DeskMotionColor.md_theme_dark_outlineVariant,
    scrim = DeskMotionColor.md_theme_dark_scrim,
)